### PR TITLE
Eulogos chat extractor

### PR DESCRIPTION
**Pull request by GianluigiMemoli**
Issue #36

### CODE REVIEW

**Comment by GianluigiMemoli** [comment]
There is other sanitization to do and I've also noticed that not all the chats are in italian

**Comment by Mte90** [comment]
It seems perfect but there are this things to do:

* strip whitespace top/bottom of sentence
* there are some lines empty
* I don't know if it is possible to remove sentence like this `miladyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy heheheheeh`
* I don't know if it is the cases to split sentences that have a `.?!` just to get more sentences to parse as single

Anyway with atleast the first 2 changes I can approve it. 
There are like 100000 sentences generated.

**Comment by mone27** [comment]
>     * I don't know if it is possible to remove sentence like this `miladyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy heheheheeh`

Maybe an idea can be to check if a pattern is repeated more than 3 or 4 times. Don't know if this can be too resource consuming and if there is a way to use a regex.

**Comment by GianluigiMemoli** [comment]
> > ```
> > * I don't know if it is possible to remove sentence like this `miladyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy heheheheeh`
> > ```
> 
> Maybe an idea can be to check if a pattern is repeated more than 3 or 4 times. Don't know if this can be too resource consuming and if there is a way to use a regex.

The 'milady' issue I think is easy resolvable, about the performances I'm giving an eye to the python's implementation of array slicing. 
About the laugh question I was thinking of removing words with just two letters from a certain length. This one I think is more expensive due to the fact that I have to compare each word's letter.

**Comment by Mte90** [comment]
Thanks is perfect now :-D

**Pull request merged**
